### ISSUE TITLE
Error: Cannot find module 'postcss'

### ISSUE THREAD

**Issue by ktr-skmt** [YNUWAIWAI/werewolf-client#28]
yarn 1.2.1
node v8.7.0
yarn buildで次のエラーが出ました

```
$ yarn build
yarn run v1.2.1
$ node tools/build.js
module.js:529
    throw err;
    ^

Error: Cannot find module 'postcss'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/ilham/Documents/werewolf-client/tools/build.js:3:17)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by ktr-skmt** [comment]
npm installをして見ました

```
$ npm install
npm notice created a lockfile as package-lock.json. You should commit this file.
added 311 packages in 22.754s
``` 

その後で，yarn buildして見たのですが，次のようになってしまいます

```
$ yarn build
yarn run v1.2.1
$ node tools/build.js
/Users/ilham/Documents/werewolf-client/tools/build.js:79
            throw err
            ^

Error: ENOENT: no such file or directory, open 'dest/module/timer.js'
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by ktr-skmt** [comment]
`cp src/module/timer.js dest/module/
`
をしたら次のようにbuildは成功しました．

```
$ yarn build
yarn run v1.2.1
$ node tools/build.js
✨  Done in 0.73s.

```

それで，どれを開けばいい？
yarn startしてlocalhost:4000みたいに開くのではなく，

`cp -r src/img dest/
`
をしてから
dist/index.htmlを開くべき？

docs/index.htmlって何？

とりあえず両方開いてみたけど次のJavaScriptのエラーがChromeブラウザ(61.0.3163.100（Official Build） （64 ビット）)のConsole上に出ていて，画面上ではタイマーが起動していなさそうです．

```
Failed to load resource: net::ERR_FILE_NOT_FOUND wolf.png
index.html:1 Access to Script at 'file:///Users/ilham/Documents/werewolf-client/dest/app.js' from origin 'null' has been blocked by CORS policy: Invalid response. Origin 'null' is therefore not allowed access.
```

**Comment by ktr-skmt** [comment]
`yarn build:watch`
したら，下のように表示されたので，http://localhost:8000/ を開いたら見られました
Console上のエラーは消えませんでしたが，とりあえず見られたのでcloseします

```
$ yarn build:watch
yarn run v1.2.1
$ node tools/build.js -w
see http://localhost:8000/
```

**Comment by nimiusrd** [comment]
console上のエラーはコミットしていない仮置きのファイル(`img/wolf.png`)を参照しているので出ていると考えられます．これに関しては置き換えをするので問題ないです．

`dest/module/timer.js`が開けない問題に関してはES Modulesを使うことにした影響でCORSの問題が出てきたことによるものです．

ES Modulesについて
https://jakearchibald.com/2017/es-modules-in-browsers/
https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Statements/import
https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Statements/export

CORSについて
https://developer.mozilla.org/ja/docs/Web/HTTP/HTTP_access_control

関連PR
#17
